version: "3.8"
services:
  smb:
    image: dperson/samba
    container_name: smbserver
    ports:
      - "139:139"
      - "4445:445"
    command: >
      -u "integration;123" -s "Recebidos;/share;yes;no;yes;all;none"
    volumes:
      - ./dados:/share

